"""empty message

Revision ID: 71b580da1adf
Revises: 1b6659d3ba67
Create Date: 2021-09-25 17:41:57.576837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b580da1adf'
down_revision = '1b6659d3ba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
