"""empty message

Revision ID: 844ba37e5006
Revises: aace78a4dac5
Create Date: 2021-09-25 17:52:29.416191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844ba37e5006'
down_revision = 'aace78a4dac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False,server_default="true"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
