"""empty message

Revision ID: aace78a4dac5
Revises: c67e14f2e3ea
Create Date: 2021-09-25 17:44:27.644405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aace78a4dac5'
down_revision = 'c67e14f2e3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
