"""empty message

Revision ID: c67e14f2e3ea
Revises: 71b580da1adf
Create Date: 2021-09-25 17:43:59.249279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67e14f2e3ea'
down_revision = '71b580da1adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True, server_default=True))
    # ### end Alembic commands ###
